name: Test Workflow
 
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow is running!"
      - run: echo "Hello, world!" > hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: hello.txt
